fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_DEFAULT_ps_4_0 
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_DEFAULT_SHADOW_ps_4_0 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_DEFAULT_OTFMASK_ps_4_0 /D OTF_MASK =1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_DEFAULT_OTFMASK_SHADOW_ps_4_0 /D OTF_MASK=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_CLIPSEMIOPAQUE_ps_4_0 /D RM_CLIPSEMIOPAQUE=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_SCULPTMASK_ps_4_0 /D SCULPTMASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_MODULATION_ps_4_0 /D RM_MODULATION=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_BASIC_MODULATION_OTFMASK_ps_4_0 /D RM_MODULATION=1 /D OTF_MASK=1

fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_DEFAULT_ps_4_0 /D RM_SURFACEEFFECT=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_DEFAULT_SHADOW_ps_4_0 /D RM_SURFACEEFFECT=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_DEFAULT_OTFMASK_ps_4_0 /D RM_SURFACEEFFECT=1 /D OTF_MASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_DEFAULT_OTFMASK_SHADOW_ps_4_0 /D RM_SURFACEEFFECT=1 /D OTF_MASK=1 /D RM_SHADOW=1 
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_CURVATURE_ps_4_0 /D RM_SURFACEEFFECT=1 /D SURFACE_MODE_CURVATURE=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_CCF_ps_4_0 /D RM_SURFACEEFFECT=1 /D SAMPLER_VOLUME_CCF=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_SURFACE_MARKER_ps_4_0 /D RM_SURFACEEFFECT=1 /D MARKERS_ON_SURFACE=1

fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_DEFAULT_ps_4_0 /D INPUT_LAYERS=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_DEFAULT_SHADOW_ps_4_0 /D INPUT_LAYERS=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_DEFAULT_OTFMASK_ps_4_0 /D INPUT_LAYERS=1 /D OTF_MASK=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_DEFAULT_OTFMASK_SHADOW_ps_4_0 /D INPUT_LAYERS=1 /D OTF_MASK=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_CLIPSEMIOPAQUE_ps_4_0 /D INPUT_LAYERS=1 /D RM_CLIPSEMIOPAQUE=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_SCULPTMASK_ps_4_0 /D INPUT_LAYERS=1 /D SCULPTMASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_MODULATION_ps_4_0 /D INPUT_LAYERS=1 /D RM_MODULATION=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_MODULATION_OTFMASK_ps_4_0 /D INPUT_LAYERS=1 /D RM_MODULATION=1 /D OTF_MASK=1 

fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_DEFAULT_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_DEFAULT_SHADOW_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_DEFAULT_OTFMASK_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D OTF_MASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_DEFAULT_OTFMASK_SHADOW_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D OTF_MASK=1 /D RM_SHADOW=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_CLIPSEMIOPAQUE_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_CLIPSEMIOPAQUE=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_SCULPTMASK_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D SCULPTMASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_MODULATION_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_MODULATION=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_LAYERS_ADV_MODULATION_OTFMASK_ps_4_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_MODULATION=1 /D OTF_MASK=1 

fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_DVR_TEST_ps_4_0 /D BLOCKSHOW=1

fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_MAX_ps_4_0 /D RM_RAYMAX=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_MAX_OTFMASK_ps_4_0 /D RM_RAYMAX=1 /D OTF_MASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_MIN_ps_4_0 /D RM_RAYMIN=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_MIN_OTFMASK_ps_4_0 /D RM_RAYMIN=1 /D OTF_MASK=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_SUM_ps_4_0 /D RM_RAYSUM=1
fxc /E PsDVR_Common /T ps_4_0 VRShader_Common.hlsl /Fo PS_XRAY_SUM_OTFMASK_ps_4_0 /D RM_RAYSUM=1 /D OTF_MASK=1

fxc /E PsDVR_ShadowMapGeneration /T ps_4_0 VRShader_Shadow.hlsl /Fo PS_DVR_BASIC_DEFAULT_SHADOWMAP_ps_4_0 
fxc /E PsDVR_ShadowMapGeneration /T ps_4_0 VRShader_Shadow.hlsl /Fo PS_DVR_BASIC_OTFMASK_SHADOWMAP_ps_4_0 /D OTF_MASK=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_DEFAULT_cs_5_0 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_DEFAULT_SHADOW_cs_5_0 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_DEFAULT_OTFMASK_cs_5_0 /D OTF_MASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_DEFAULT_OTFMASK_SHADOW_cs_5_0 /D OTF_MASK=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_CLIPSEMIOPAQUE_cs_5_0 /D RM_CLIPSEMIOPAQUE=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_SCULPTMASK_cs_5_0 /D SCULPTMASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_MODULATION_cs_5_0 /D RM_MODULATION=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_BASIC_MODULATION_OTFMASK_cs_5_0 /D RM_MODULATION=1 /D OTF_MASK=1 /D __CS_MODEL=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_DEFAULT_cs_5_0 /D RM_SURFACEEFFECT=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_DEFAULT_SHADOW_cs_5_0 /D RM_SURFACEEFFECT=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_DEFAULT_OTFMASK_cs_5_0 /D RM_SURFACEEFFECT=1 /D OTF_MASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_DEFAULT_OTFMASK_SHADOW_cs_5_0 /D RM_SURFACEEFFECT=1 /D OTF_MASK=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_CURVATURE_cs_5_0 /D RM_SURFACEEFFECT=1 /D SURFACE_MODE_CURVATURE=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_CCF_cs_5_0 /D RM_SURFACEEFFECT=1 /D SAMPLER_VOLUME_CCF=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_SURFACE_MARKER_cs_5_0 /D RM_SURFACEEFFECT=1 /D MARKERS_ON_SURFACE=1 /D __CS_MODEL=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_DEFAULT_cs_5_0 /D INPUT_LAYERS=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_DEFAULT_SHADOW_cs_5_0 /D INPUT_LAYERS=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_DEFAULT_OTFMASK_cs_5_0 /D INPUT_LAYERS=1 /D OTF_MASK=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_DEFAULT_OTFMASK_SHADOW_cs_5_0 /D INPUT_LAYERS=1 /D OTF_MASK=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_CLIPSEMIOPAQUE_cs_5_0 /D INPUT_LAYERS=1 /D RM_CLIPSEMIOPAQUE=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_SCULPTMASK_cs_5_0 /D INPUT_LAYERS=1 /D SCULPTMASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_MODULATION_cs_5_0 /D INPUT_LAYERS=1 /D RM_MODULATION=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_MODULATION_OTFMASK_cs_5_0 /D INPUT_LAYERS=1 /D RM_MODULATION=1 /D OTF_MASK=1 /D __CS_MODEL=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_DEFAULT_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_DEFAULT_SHADOW_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_DEFAULT_OTFMASK_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D OTF_MASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_DEFAULT_OTFMASK_SHADOW_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D OTF_MASK=1 /D RM_SHADOW=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_CLIPSEMIOPAQUE_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_CLIPSEMIOPAQUE=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_SCULPTMASK_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D SCULPTMASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_MODULATION_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_MODULATION=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_LAYERS_ADV_MODULATION_OTFMASK_cs_5_0 /D INPUT_LAYERS=1 /D ZSLAB_BLENDING=1 /D RM_MODULATION=1 /D OTF_MASK /D __CS_MODEL=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_DVR_TEST_cs_5_0 /D BLOCKSHOW=1 /D __CS_MODEL=1

fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_MAX_cs_5_0 /D RM_RAYMAX=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_MAX_OTFMASK_cs_5_0 /D RM_RAYMAX=1 /D OTF_MASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_MIN_cs_5_0 /D RM_RAYMIN=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_MIN_OTFMASK_cs_5_0 /D RM_RAYMIN /D OTF_MASK=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_SUM_cs_5_0 /D RM_RAYSUM=1 /D __CS_MODEL=1
fxc /E CsDVR_Common /T cs_5_0 VRShader_Common.hlsl /Fo CS_XRAY_SUM_OTFMASK_cs_5_0 /D RM_RAYSUM=1 /D OTF_MASK=1 /D __CS_MODEL=1

fxc /E CsDVR_ShadowMapGeneration /T cs_5_0 VRShader_Shadow.hlsl /Fo CS_DVR_BASIC_DEFAULT_SHADOWMAP_cs_5_0 /D __CS_MODEL=1
fxc /E CsDVR_ShadowMapGeneration /T cs_5_0 VRShader_Shadow.hlsl /Fo CS_DVR_BASIC_OTFMASK_SHADOWMAP_cs_5_0 /D OTF_MASK=1 /D __CS_MODEL=1

