fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_MARKERSONSURFACE_ps_4_0 /D PS_COLOR_GLOBAL /D MARKERS_ON_SURFACE
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_MAXSHADING_MARKERSONSURFACE_ps_4_0 /D PS_MAX_IILUMINATION /D PS_COLOR_GLOBAL /D MARKERS_ON_SURFACE

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_SHADOW_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D OTF_MASK /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_MARKERSONSURFACE_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK /D MARKERS_ON_SURFACE
