
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_DEFAULT_cs_4_0 /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_MODULATION_cs_4_0 /D RM_MODULATION /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_SHADOW_cs_4_0 /D RM_SHADOW /D OTF_MASK

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_DEFAULT_cs_4_0 /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_MODULATION_cs_4_0 /D RM_MODULATION /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SHADOW_cs_4_0 /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACECURVATURE_cs_4_0 /D RM_SURFACEEFFECT /D SURFACE_MODE_CURVATURE /D VR_LAYER_OUT /D OTF_MASK

fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_MASK_SHADOW_cs_4_0 /D OTF_MASK
fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_MASK_SURFACE_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D OTF_MASK
