// FEATURE LEVEL 10_0 //
fxc /E CommonVS_OnlyPoint /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_P_vs_4_0
fxc /E CommonVS_PN /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PN_vs_4_0 
fxc /E CommonVS_PT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PT_vs_4_0
fxc /E CommonVS_PNT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PNT_vs_4_0 
fxc /E CommonVS_PTTT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PTTT_vs_4_0 
fxc /E CommonVS_PNT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PNT_DEV_vs_4_0 /D VS_POINTDEVIATIRON
fxc /E ProxyVS_Point /T vs_4_0 MergeAndSuperimpose.hlsl /Fo SR_PROJ_PROXY_vs_4_0 /D PROXY_PS

fxc /E CommonVS_OnlyPoint /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_P_MVB_vs_4_0 /D VS_MINUSVIEWBOX
fxc /E CommonVS_PN /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PN_MVB_vs_4_0 /D VS_MINUSVIEWBOX
fxc /E CommonVS_PT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PT_MVB_vs_4_0 /D VS_MINUSVIEWBOX
fxc /E CommonVS_PNT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PNT_MVB_vs_4_0 /D VS_MINUSVIEWBOX
fxc /E CommonVS_PNT /T vs_4_0 SRShader_Common.hlsl /Fo SR_PROJ_PNT_DEV_MVB_vs_4_0 /D VS_POINTDEVIATIRON /D VS_MINUSVIEWBOX

//fxc /E CommonPS_TEXCOORD1 /T ps_4_0 SRShader_Common.hlsl /Fo SR_PLANE_MAPPING_TEX1_ps_4_0 /D VS_MINUSVIEWBOX
//fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PLANE_PHONG_TEX1COLOR_ps_4_0 /D VS_MINUSVIEWBOX
//fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PLANE_PHONG_GLOBALCOLOR_ps_4_0 /D PS_COLOR_GLOBAL /D VS_MINUSVIEWBOX
//fxc /E CommonPS_AirwayColorMapping /T ps_4_0 SRShader_Common.hlsl /Fo SR_PLANE_AIRWAYANALYSIS_ps_4_0 /D VS_MINUSVIEWBOX
//fxc /E CommonPS_CMM_TEXT /T ps_4_0 SRShader_Common.hlsl /Fo SR_PLANE_VOXELIZATION_ps_4_0

fxc /E CommonPS_TEXCOORD1 /T ps_4_0 SRShader_Common.hlsl /Fo SR_MAPPING_TEX1_ps_4_0
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_TEX1COLOR_ps_4_0
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_ps_4_0 /D PS_COLOR_GLOBAL
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_MAXSHADING_ps_4_0 /D PS_MAX_IILUMINATION /D PS_COLOR_GLOBAL
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_MARKERSONSURFACE_ps_4_0 /D PS_COLOR_GLOBAL /D MARKERS_ON_SURFACE
fxc /E CommonPS_PhongShading /T ps_4_0 SRShader_Common.hlsl /Fo SR_PHONG_GLOBALCOLOR_MAXSHADING_MARKERSONSURFACE_ps_4_0 /D PS_MAX_IILUMINATION /D PS_COLOR_GLOBAL /D MARKERS_ON_SURFACE
fxc /E CommonPS_Superimpose /T ps_4_0 SRShader_Common.hlsl /Fo SR_VOLUME_SUPERIMPOSE_ps_4_0
fxc /E CommonPS_Deviation /T ps_4_0 SRShader_Common.hlsl /Fo SR_VOLUME_DEVIATION_ps_4_0
fxc /E CommonPS_CMM_LINE /T ps_4_0 SRShader_Common.hlsl /Fo SR_CMM_LINE_ps_4_0
fxc /E CommonPS_CMM_TEXT /T ps_4_0 SRShader_Common.hlsl /Fo SR_CMM_TEXT_ps_4_0
fxc /E CommonPS_CMM_MultiTEXTs /T ps_4_0 SRShader_Common.hlsl /Fo SR_CMM_MULTI_TEXTS_ps_4_0
fxc /E CommonPS_ImageStackMapping /T ps_4_0 SRShader_Common.hlsl /Fo SR_IMAGESTACK_MAP_ps_4_0
fxc /E CommonPS_AirwayColorMapping /T ps_4_0 SRShader_Common.hlsl /Fo SR_AIRWAYANALYSIS_ps_4_0

// Volume Renderer //
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_DEFAULT_cs_4_0
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MODULATION_cs_4_0 /D RM_MODULATION
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_SHADOW_cs_4_0 /D RM_SHADOW
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_DEFAULT_SCULPTMASK_cs_4_0 /D SCULPTMASK

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BLOCK_IND_SHOW_cs_4_0 /D BLOCKSHOW /D VR_LAYER_OUT

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_DEFAULT_cs_4_0 /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MODULATION_cs_4_0 /D RM_MODULATION /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SHADOW_cs_4_0 /D RM_SHADOW /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_DEFAULT_SCULPTMASK_cs_4_0 /D SCULPTMASK /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACEEFFECT_SHADOW_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_CCF_SURFACEEFFECT_cs_4_0 /D RM_SURFACEEFFECT /D SAMPLER_VOLUME_CCF /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_SURFACECURVATURE_cs_4_0 /D RM_SURFACEEFFECT /D SURFACE_MODE_CURVATURE /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_RAYMAX_cs_4_0 /D RM_RAYMAX /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_RAYMIN_cs_4_0 /D RM_RAYMIN /D VR_LAYER_OUT
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_RAYSUM_cs_4_0 /D RM_RAYSUM /D VR_LAYER_OUT

fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_SHADOW_cs_4_0
fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_SURFACE_SHADOW_cs_4_0 /D RM_SURFACEEFFECT

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_DEFAULT_cs_4_0 /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_MODULATION_cs_4_0 /D RM_MODULATION /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_MASK_SHADOW_cs_4_0 /D RM_SHADOW /D OTF_MASK

fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_DEFAULT_cs_4_0 /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_CLIPSEMIOPAQUE_cs_4_0 /D RM_CLIPSEMIOPAQUE /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_MODULATION_cs_4_0 /D RM_MODULATION /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SHADOW_cs_4_0 /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_MARKERSONSURFACE_cs_4_0 /D RM_SURFACEEFFECT /D VR_LAYER_OUT /D OTF_MASK /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACEEFFECT_MARKERSONSURFACE_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT /D OTF_MASK /D MARKERS_ON_SURFACE
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_MASK_SURFACECURVATURE_cs_4_0 /D RM_SURFACEEFFECT /D SURFACE_MODE_CURVATURE /D VR_LAYER_OUT /D OTF_MASK

fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_MASK_SHADOW_cs_4_0 /D OTF_MASK
fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_VOLUME_GEN_MASK_SURFACE_SHADOW_cs_4_0 /D RM_SURFACEEFFECT /D OTF_MASK

fxc /E MergeLayers /T cs_4_0 MergeAndSuperimpose.hlsl /Fo MERGE_SROUT_AND_LAYEROUT_TO_LAYEROUT_cs_4_0 /D SROUT_AND_LAYEROUT_TO_LAYEROUT
fxc /E MergeLayers /T cs_4_0 MergeAndSuperimpose.hlsl /Fo MERGE_LAYEROUT_TO_RENDEROUT_cs_4_0 /D LAYEROUT_TO_RENDEROUT

fxc /E MergeLayers /T ps_4_0 MergeAndSuperimpose.hlsl /Fo PS_MERGE_SROUT_LOD2X_AND_LAYEROUT_TO_LAYEROUT_ps_4_0 /D SROUT_AND_LAYEROUT_TO_LAYEROUT /D PROXY_PS /D PROXY_PS_LOD_2X
fxc /E MergeLayers /T ps_4_0 MergeAndSuperimpose.hlsl /Fo PS_MERGE_SROUT_AND_LAYEROUT_TO_LAYEROUT_ps_4_0 /D SROUT_AND_LAYEROUT_TO_LAYEROUT /D PROXY_PS
fxc /E MergeLayers /T ps_4_0 MergeAndSuperimpose.hlsl /Fo PS_MERGE_LAYEROUT_TO_RENDEROUT_ps_4_0 /D LAYEROUT_TO_RENDEROUT /D PROXY_PS

fxc /E VRCS_Experiment /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_SIMULTANEOUS_cs_4_0

fxc /E VRCS_Experiment /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_SIMULTANEOUS_THREE_cs_4_0 /D THREE_SIMULTANEOUS_MIX
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_MIX_DEFAULT_HOMOGENEOUS_cs_4_0 /D HOMOGENEOUS
fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_VOLUME_IND_DEFAULT_HOMOGENEOUS_cs_4_0 /D VR_LAYER_OUT /D HOMOGENEOUS

//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_MIX_DEFAULT_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_MIX_SHADOW_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SHADOW
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_IND_DEFAULT_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D VR_LAYER_OUT
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_IND_SHADOW_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SHADOW /D VR_LAYER_OUT
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_IND_SURFACEEFFECT_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SURFACEEFFECT /D VR_LAYER_OUT
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_IND_SURFACEEFFECT_SHADOW_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SURFACEEFFECT /D RM_SHADOW /D VR_LAYER_OUT
//fxc /E VRCS_Common /T cs_4_0 VRShader_Common.hlsl /Fo DVR_BRICK_IND_CCF_SURFACEEFFECT_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SURFACEEFFECT /D SAMPLER_VOLUME_CCF /D VR_LAYER_OUT
//fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_BRICK_GEN_SHADOW_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK
//fxc /E VRCS_GenShadowMap /T cs_4_0 VRShader_Shadow.hlsl /Fo DVR_BRICK_GEN_SURFACE_SHADOW_cs_4_0 /D SAMPLE_FROM_BRICKCHUNK /D RM_SURFACEEFFECT
